### PR TITLE
MAINT fix circleci root directory

### PR DESCRIPTION
**Pull request by glemaitre**
Cont'd #21

### CODE REVIEW

**Comment by glemaitre** [comment]
OK we need to remove the "/0/" in the URL from the parallel build number.

**Comment by GaelVaroquaux** [comment]
Current artifacts: https://3-246408325-gh.circle-artifacts.com/0/index.html

Either remove the "/0/" from the artifact URL, or add it to the generated html (not great)

**Comment by glemaitre** [comment]
I am not finding anywhere in the CircleCI documentation on how to remove this Parallel Number. I think that the fastest way would be to inject the build number even if it is kind of dirty. We could do that only as a post-processing job to publish the artefacts.

**Comment by GaelVaroquaux** [comment]
> We could do that only as a post-processing job to publish the artefacts.

I'm fine with that.

**Comment by glemaitre** [comment]
I will not be able to finish tonight. Changing the path in the index.html is not enough. We also need "sourceMappingURL" I think by prepending "/0/"

**Pull request merged**
