### PR TITLE
Normalize the time series by the pop of a country

### LINKED ISSUE #8: Plot rates by default in addition to numbers?
there are various ways in which one might normalize the count data that could be relevant to understanding and prediction.  for example, per capita, per # of hosiptal beds, per square mile, etc.

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Fixes #8

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
This is ready for review (for instance looking at the artifacts).  cc @poldrack

**Comment by poldrack** [comment]
how do I access the artifacts?

**Comment by emmanuelle** [comment]
There seems to be something wrong with the lower bound prediction 
image (consistent across countries)

**Comment by poldrack** [comment]
looks like the lower bound might be getting doubly logged?

**Comment by emmanuelle** [comment]
@poldrack click on the "show all checks" link in the "all checks have passed" then on the "details" link in "ci/circleci: python3 artifact — Link to 0/index.html"

**Comment by poldrack** [comment]
otherwise LGTM!

**Comment by GaelVaroquaux** [comment]
The lower bound was indeed wrong. I've pushed a fix.

**Comment by poldrack** [comment]
new version looks good to me!

**Comment by emmanuelle** [comment]
Merging, thanks!

**Pull request merged**
