### PR TITLE
[MRG] Table mobile friendly too

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Test to see if I can make the table mobile friendly too

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Doesn't work on an android phone. We will have to use media queries, I fear.

**Comment by GaelVaroquaux** [comment]
OK, that did not work.

We probably need to increase a bit the font size of this table via a media query for high DPI devices: https://gist.github.com/marcedwards/3446599

**Comment by GaelVaroquaux** [comment]
Just checked on my phone: this is much better; I'll improve it a bit more.

**Comment by GaelVaroquaux** [comment]
Not yet ready...

**Comment by GaelVaroquaux** [comment]
Can people check on their device what their DPI is: visit the following URL: https://www.infobyip.com/detectmonitordpi.php and tell me here your device and your DPI

**Comment by GaelVaroquaux** [comment]
Samsung S7 phone: DPI 384 x 384

**Comment by emmanuelle** [comment]
Samsung A5: 288x288

**Comment by GaelVaroquaux** [comment]
Also useful: list of devices and DPI: http://dpi.lv/

**Comment by emmanuelle** [comment]
older Samsung Galaxy phone (don't know exact model): 288x288

**Comment by GaelVaroquaux** [comment]
This is finally ready to merge. The website is somewhat usable on mobile phone.

**Comment by emmanuelle** [comment]
ok let me take a look!

**Comment by GaelVaroquaux** [comment]
> ok let me take a look!

On a mobile phone :)

**Comment by GaelVaroquaux** [comment]
Merge?

**Comment by emmanuelle** [comment]
Looks good about font sizes. The reactivity of the table is quite poor on my mobile phone, but it does not come from your PR, so merging.

**Comment by GaelVaroquaux** [comment]
Yes, the reactivity of the table is very bad. This is why I frown on adding information.

Turning off the javascript on selection of cells of the table might help (the less javascript the better, I would think).

**Pull request merged**
