### PR TITLE
Don't scale table on high-DPI computer screens

### PR DESCRIPTION
**Pull request by GaelVaroquaux**

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Tries to address https://twitter.com/_psyguy/status/1242898806502555649

**Comment by emmanuelle** [comment]
on which device should this be tested?

**Comment by GaelVaroquaux** [comment]
> on which device should this be tested?

A computer with a very high DPI screen. Some users have been complaining
about the layout. I think that they have high-end computer (eg expensive
macs).

**Comment by emmanuelle** [comment]
ah ok. So maybe we could ask @nicolaskruchten to see if the layout of the artifact here is better than the one of the deployed version?

**Comment by GaelVaroquaux** [comment]
@nikohansen was also having suboptimal layouts

**Comment by GaelVaroquaux** [comment]
If I get no feedback on this before a few minutes (bedtime), I think that I'll merge it, as it does solve some problems (though not all).

**Pull request merged**
